[services] Tunnelbroker - Fix `DatabaseManagerTest.cpp` build error on non-closed brackets
Summary:

Fix `DatabaseManagerTest.cpp` build error on non-closed brackets which was discovered during the new builds:

```
DatabaseManagerTest.cpp:185:80: error: expected ')'
[build]       "mobile:EMQNoQ7b2ueEmQ4QsevRWlXxFCNt055y20T1PHdoYAQRt0S6TLzZWNM6XSvdWqxm";
```

Test Plan:

Run yarn test-tunnelbroker-service to build and run the tests.

Reviewers:

Subscribers: